openapi: 3.0.0
info:
  title: CommentService API
  version: 1.0.0
  description: 댓글 서비스에 대한 API 문서입니다.
tags:
  - name: Comment
    description: 댓글 관련 API

paths:
  /api/comments:
    post:
      summary: 댓글 작성
      description: 댓글을 작성하는 기능입니다. 유저가 로그인되어 있어야 합니다.
      tags:
        - Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - postId
                - content
              properties:
                postId:
                  type: integer
                  description: 댓글을 작성할 게시물의 ID
                content:
                  type: string
                  description: 작성할 댓글의 내용
                parentId:
                  type: integer
                  description: 부모 댓글의 ID (대댓글인 경우)
      responses:
        '201':
          description: 댓글 작성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 요청 실패 - 유저가 로그인되어 있지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 에러 - 댓글 작성 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/comments/post/{postId}:
    get:
      summary: 게시물의 댓글 조회
      description: 특정 게시물에 달린 모든 댓글을 조회합니다. 유저가 로그인되어 있어야 합니다.
      tags:
        - Comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
          description: 조회할 게시물의 ID
      responses:
        '200':
          description: 댓글 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        commentId:
                          type: integer
                        postId:
                          type: integer
                        content:
                          type: string
                        memberId:
                          type: integer
                        parentId:
                          type: integer
        '400':
          description: 요청 실패 - 유저가 로그인되어 있지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 에러 - 댓글 조회 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/comments/{commentId}/post/{postId}:
    delete:
      summary: 댓글 삭제
      description: 특정 댓글을 삭제하는 기능입니다. 유저가 로그인되어 있어야 합니다.
      tags:
        - Comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
          description: 댓글이 달린 게시물의 ID
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
          description: 삭제할 댓글의 ID
      responses:
        '200':
          description: 댓글 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 요청 실패 - 유저가 로그인되어 있지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 에러 - 댓글 삭제 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/comments/{commentId}/post/{postId}/like:
    post:
      summary: 댓글 좋아요 추가
      description: 특정 댓글에 좋아요를 추가하는 기능입니다. 유저가 로그인되어 있어야 합니다.
      tags:
        - Comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
          description: 좋아요를 추가할 댓글이 달린 게시물의 ID
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
          description: 좋아요를 추가할 댓글의 ID
      responses:
        '200':
          description: 댓글 좋아요 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 요청 실패 - 유저가 로그인되어 있지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 에러 - 댓글 좋아요 추가 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/comments/{commentId}/post/{postId}/warning:
    post:
      summary: 댓글 신고 추가
      description: 특정 댓글을 신고하는 기능입니다. 유저가 로그인되어 있어야 합니다.
      tags:
        - Comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
          description: 신고를 추가할 댓글이 달린 게시물의 ID
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
          description: 신고를 추가할 댓글의 ID
      responses:
        '200':
          description: 댓글 신고 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 요청 실패 - 유저가 로그인되어 있지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 에러 - 댓글 신고 추가 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
