openapi: 3.0.0
info:
  title: Notice4MusicalTicketing
  version: 1.0.0
  description: Musical ticketing service API
tags:
  - name: dataFetch
    description: API for fetching musical data

paths:
  /api/data/fetchAndStore:
    post:
      summary: Fetch and store data from external API
      description: Fetches data from an external OpenAPI and stores it in the MySQL database.
      tags:
        - dataFetch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  example: "20240101"
                endDate:
                  type: string
                  example: "20240131"
                genre:
                  type: string
                  example: "뮤지컬"
                region:
                  type: string
                  example: "서울"
      responses:
        200:
          description: Data fetched and stored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Data fetched and stored successfully"
        500:
          description: Internal server error

  /api/data/musicals:
    get:
      summary: Get list of musicals
      description: Retrieves a list of musicals with basic details.
      tags:
        - dataFetch
      parameters:
        - name: genre
          in: query
          schema:
            type: string
            example: "뮤지컬"
      responses:
        200:
          description: Musical list retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  musicals:
                    type: array
                    items:
                      type: object
                      properties:
                        mt20id:
                          type: string
                          example: "12345"
                        title:
                          type: string
                          example: "Example Musical"
                        region:
                          type: string
                          example: "서울"
                        startDate:
                          type: string
                          example: "2024-01-01"
                        endDate:
                          type: string
                          example: "2024-01-31"
                        posterImage:
                          type: string
                          example: "poster.jpg"
        500:
          description: Internal server error

  /api/data/musicals/{mt20id}:
    get:
      summary: Get musical details
      description: Fetch detailed data for a specific musical.
      tags:
        - dataFetch
      parameters:
        - in: path
          name: mt20id
          required: true
          schema:
            type: string
          description: The ID of the musical
      responses:
        200:
          description: Musical details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  mt20id:
                    type: string
                    example: "12345"
                  title:
                    type: string
                    example: "Example Musical"
                  genre:
                    type: string
                    example: "뮤지컬"
                  region:
                    type: string
                    example: "서울"
                  startDate:
                    type: string
                    example: "2024-01-01"
                  endDate:
                    type: string
                    example: "2024-01-31"
                  cast:
                    type: string
                    example: "Actor1, Actor2"
                  runtime:
                    type: integer
                    example: 120
                  ageRating:
                    type: string
                    example: "12+"
                  productionCompany:
                    type: string
                    example: "Example Production"
                  ticketPrice:
                    type: string
                    example: "50000"
                  synopsis:
                    type: string
                    example: "Brief synopsis here..."
                  introImages:
                    type: array
                    items:
                      type: string
                      example: "http://example.com/intro1.jpg"
                  showtimes:
                    type: string
                    example: "Fri 18:00, Sat 14:00"
                  facilityDetails:
                    type: string
                    example: "Example Facility"
        404:
          description: Musical not found

  /api/data/admin/insert:
    post:
      summary: Insert a new musical (Admin)
      description: Allows admin to insert detailed musical information.
      tags:
        - dataFetch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Example Musical"
                region:
                  type: string
                  example: "서울"
                startDate:
                  type: string
                  example: "2024-01-01"
                endDate:
                  type: string
                  example: "2024-01-31"
                posterImage:
                  type: string
                  example: "poster.jpg"
                genre:
                  type: string
                  example: "뮤지컬"
                cast:
                  type: string
                  example: "Actor1, Actor2"
                runtime:
                  type: integer
                  example: 120
                ageRating:
                  type: string
                  example: "12+"
                productionCompany:
                  type: string
                  example: "Example Production"
                ticketPrice:
                  type: string
                  example: "50000"
                synopsis:
                  type: string
                  example: "Brief synopsis here..."
                introImages:
                  type: array
                  items:
                    type: string
                    example: "http://example.com/intro1.jpg"
                showtimes:
                  type: string
                  example: "Fri 18:00, Sat 14:00"
                facilityDetails:
                  type: string
                  example: "Example Facility"
      responses:
        201:
          description: Musical inserted successfully
        500:
          description: Internal server error
