openapi: 3.0.0
info:
  title: Notice4MusicalTicketing
  version: 1.0.0
  description: 야호 ^_^'
tags:
  - name: Post
    description: 게시물 관리

paths:
  /api/post:
    post:
      summary: 게시물 작성
      description: |
        게시글을 새로 작성합니다.
        제목, 내용, 카테고리를 포함합니다.
      tags:
        - Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - category
              properties:
                title:
                  type: string
                content:
                  type: string
                category:
                  type: string
      responses:
        '201':
          description: 게시물 작성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 오류로 인한 게시물 작성 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  error:
                    type: string

  /api/post/{postId}:
    delete:
      summary: 게시물 삭제
      description: 특정 게시물을 삭제합니다.
      tags:
        - Post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
          description: 삭제할 게시물의 ID
      responses:
        '200':
          description: 게시물 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

    get:
      summary: 특정 게시물 조회
      description: 특정 게시물의 상세 정보를 조회합니다.
      tags:
        - Post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
          description: 조회할 게시물의 ID
      responses:
        '200':
          description: 게시물 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  post:
                    type: object
                    properties:
                      postId:
                        type: integer
                      memberId:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time
                      likeCount:
                        type: integer
                      warningCount:
                        type: integer
                      replyCount:
                        type: integer
                      views:
                        type: integer
                      category:
                        type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

    patch:
      summary: 게시물 수정
      description: 특정 게시물의 내용을 수정합니다.
      tags:
        - Post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
          description: 수정할 게시물의 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: 게시물 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/post/preview:
    get:
      summary: 모든 게시물 미리보기 조회 및 게시물 검색
      description: 모든 게시물의 미리보기 및 카테고리 별 게시물 조회와 게시물 검색 기능을 합니다.
      tags:
        - Post
      parameters:
        - in: query
          name: category
          schema:
            type: string
            enum: ["review", "friend", "deal"]
          description: 카테고리 필터
        - in: query
          name: criteria
          schema:
            type: string
          description: 검색 기준
      responses:
        '200':
          description: 게시물 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        postId:
                          type: integer
                        nickname:
                          type: string
                        title:
                          type: string
                        likeCount:
                          type: integer
                        replyCount:
                          type: integer
                        category:
                          type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/post/hot:
    get:
      summary: 인기 게시물 조회
      description: 현재 가장 인기 있는 게시물을 조회합니다.
      tags:
        - Post
      responses:
        '200':
          description: 인기 게시물 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  hotPost:
                    type: object
                    properties:
                      postId:
                        type: integer
                      title:
                        type: string
                      likeCount:
                        type: integer
                      replyCount:
                        type: integer
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/post/{postId}/like:
    post:
      summary: 게시물 추천
      description: 특정 게시물에 추천을 추가합니다.
      tags:
        - Post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
          description: 추천할 게시물의 ID
      responses:
        '201':
          description: 게시물 추천 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/post/{postId}/warning:
    post:
      summary: 게시물 신고
      description: 특정 게시물을 신고합니다.
      tags:
        - Post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
          description: 신고할 게시물의 ID
      responses:
        '201':
          description: 게시물 신고 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
