openapi: 3.0.0
info:
  title: Notice4MusicalTicketing - Review API
  version: 1.0.0
  description: 리뷰 관련 API입니다.
tags:
  - name: Review
    description: 리뷰 관리

paths:
  /api/review:
    post:
      summary: 리뷰 작성
      description: |
        새로운 리뷰를 작성합니다.
        평점, 내용, 뮤지컬 ID를 포함합니다.
      tags:
        - Review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - rating
                - musicalId
              properties:
                content:
                  type: string
                  description: 리뷰 내용
                rating:
                  type: integer
                  description: 평점 (1-5)
                musicalId:
                  type: integer
                  description: 리뷰할 뮤지컬의 ID
      responses:
        '201':
          description: 리뷰 작성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 오류로 인한 리뷰 작성 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/review/{musicalId}:
    get:
      summary: 특정 뮤지컬에 대한 리뷰 조회
      description: 특정 뮤지컬에 대한 모든 리뷰를 조회합니다.
      tags:
        - Review
      parameters:
        - in: path
          name: musicalId
          required: true
          schema:
            type: integer
          description: 조회할 뮤지컬의 ID
        - in: query
          name: cursor
          schema:
            type: string
          description: 페이지네이션을 위한 커서
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 20
          description: 페이지 당 리뷰 개수
      responses:
        '200':
          description: 리뷰 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  reviews:
                    type: array
                    items:
                      type: object
                      properties:
                        reviewId:
                          type: integer
                        content:
                          type: string
                        rating:
                          type: integer
                        averageRating:
                          type: number
                          format: float
                        musicalId:
                          type: integer
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string

  /api/review/{reviewId}/warning:
    post:
      summary: 리뷰 신고
      description: 특정 리뷰를 신고합니다.
      tags:
        - Review
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: integer
          description: 신고할 리뷰의 ID
      responses:
        '201':
          description: 리뷰 신고 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 유효하지 않은 요청 또는 인증되지 않은 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
        '404':
          description: 리뷰를 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  message:
                    type: string
